version: "3.8"

services:
  web:
    env_file: .env
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:80"
    restart: unless-stopped
    networks:
      pancakelock-api:
  redis:
    image: "redis:alpine"
    networks:
      pancakelock-api:

networks:
  pancakelock-api:

